In [1]:
# Assignment Session 6 by Sreedhara Jagatagar Sreenivasa
#Problem Statement 1:
#Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers 
#is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is 
#the input vector raised element-wise to the power of N - i - 1.
#HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

#Solution Using both vander and column_stack built-in functions

#import a numpy Array
import numpy as np

#define a function using Vander built-inin fuction for columns of the output matrix are powers of the input vector.
def matrixfuncVander(vector,N):
    #call vander function and pass the boolean as "False" to determine the order of the power.
    return np.vander(vector, increasing=False, N=N)

#define a function using column_stack built-in function for columns of the output matrix are powers of the input vector.
def matrixfuncColStack(vector,N):
    #call column_stack function.
    return np.column_stack([vector**(N-1-i) for i in range(N)])

#create a vector
vector = np.array([0,1,2,3,4,5,6,7,8,9])

#print the vector generated.
print('Vector will be passed as below :')
print(vector)

print('   ')

print(' ***********Output Matrix are Power of the input vector using Vander built-in************  ')
print('   ')

#call matrixfuncVander function by passing vector and store in a Array
powerMatrix=matrixfuncVander(vector,8)

#print the output of above function
print(powerMatrix)

print('   ')
print(' ***********Output Matrix are Power of the input vector using column_stack built-in************  ')
print('   ')

#call matrixfuncColStack function by passing vector and store in a Array
powerMatrix=matrixfuncColStack(vector,8)

#print the output of above function
print(powerMatrix)

print('   ')
print('****************************** End ******************************')

Vector will be passed as below :
[0 1 2 3 4 5 6 7 8 9]
   
 ***********Output Matrix are Power of the input vector using Vander built-in************  
   
[[      0       0       0       0       0       0       0       1]
 [      1       1       1       1       1       1       1       1]
 [    128      64      32      16       8       4       2       1]
 [   2187     729     243      81      27       9       3       1]
 [  16384    4096    1024     256      64      16       4       1]
 [  78125   15625    3125     625     125      25       5       1]
 [ 279936   46656    7776    1296     216      36       6       1]
 [ 823543  117649   16807    2401     343      49       7       1]
 [2097152  262144   32768    4096     512      64       8       1]
 [4782969  531441   59049    6561     729      81       9       1]]
   
 ***********Output Matrix are Power of the input vector using column_stack built-in************  
   
[[      0       0       0       0       0       0       0       1]
 